name: Test Email Action

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Test Email from GitHub Actions'
          to: ${{ secrets.REPORT_RECIPIENT }}
          from: Playwright Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            <h2>Test Email</h2>
            <p>This is a test email sent from GitHub Actions to verify the email configuration.</p>